apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: custom-env-
spec:
  taskSpec:
    steps:
    - image: public.ecr.aws/ubuntu/ubuntu:latest
      script: |
        #!/usr/bin/env bash
        [[ $MY_VAR1 == foo ]]
      env:
      - name: MY_VAR1
        value: foo
