apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: workingdir-
spec:
  taskSpec:
    steps:
    - name: default
      image: public.ecr.aws/ubuntu/ubuntu:latest
      workingDir: /workspace
      script: |
        #!/usr/bin/env bash
        [[ $PWD == /workspace ]]

    - name: override
      image: public.ecr.aws/ubuntu/ubuntu:latest
      workingDir: '/a/path/too/far'
      script: |
        #!/usr/bin/env bash
        [[ $PWD == /a/path/too/far ]]
